version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 3G
        reservations:
          cpus: "2"
          memory: 3G
  ################################################
  db:
    container_name: bs_db
    image: mongo:3.4.24-xenial
    ports:
      - 27717:27017
    volumes:
      - /data/mongo:/data/db
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: 10G
        reservations:
          cpus: "2"
          memory: 3G
  ################################################
  gateway:
    container_name: bs_gw
    build: './api-gateway'
    image: vahidmostofi/bookstore_gateway
    restart: on-failure
    ports:
      - "9080:9080"
    depends_on:
      - auth
    environment: 
      - JWT_KEY=someKeyIsGoodAndSomeOfThemBNoGEo1ioD!
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "1"
          memory: 10G
        reservations:
          cpus: "1"
          memory: 2G
  ################################################
  auth:
    container_name: bs_auth
    build: './auth-service'
    image: vahidmostofi/bookstore_auth
    ports:
      - "3007:3007"
    environment:
      - WorkerCount=3
      - MONGODB_URL=mongodb://db:27017/bookstoreDB
      - JWT_KEY=someKeyIsGoodAndSomeOfThemBNoGEo1ioD!
      - PORT=3007
    depends_on:
      - db
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "1"
          memory: 10G
        reservations:
          cpus: "1"
          memory: 2G
  ################################################
  books:
    container_name: bs_books
    image: vahidmostofi/bookstore_books
    build: './book-service'
    ports:
      - "3009:3009"
    environment:
      - WorkerCount=3
      - MONGODB_URL=mongodb://db:27017/bookstoreDB
      - PORT=3009
    depends_on:
      - db
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1"
          memory: 10G
        reservations:
          cpus: "1"
          memory: 2G