apiVersion: apps/v1
kind: Deployment
metadata:
  name: books
spec:
  selector:
    matchLabels:
      app: books
  replicas: 1
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
        - name: app
          image: vahidmostofi/bookstore_books
          ports:
            - containerPort: 3009
          env:
            - name: WorkerCount
              value: "1"
            - name: JAEGER_SERVICE_NAME
              value: "books"
            - name: PORT
              value: "3009"
            - name: MONGODB_URL
              value: "mongodb://mongo:27017/bookstoreDB"
            - name: JAEGER_COLLECTOR_HOST
              value: "jaeger-collector"
            - name: JAEGER_COLLECTOR_PORT
              value: "14268"
            - name: JAEGER_AGENT_HOST
              value: "jaeger-agent"
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: SAMPELLING_PROB
              value: "1"
          resources:
            requests:
              memory: "256Mi"
              cpu: 0.25
            limits:
              memory: "256Mi"
              cpu: 0.25
---
apiVersion: v1
kind: Service
metadata:
  name: books
spec:
  selector:
    app: books
  ports:
    - port: 3009
      targetPort: 3009
  type: ClusterIP
