apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: app
          image: vahidmostofi/bookstore_entry
          ports:
            - containerPort: 8080
          env:
            - name: WorkerCount
              value: "1"
            - name: JWT_KEY
              value: "someKeyIsGoodAndSomeOfThemBNoGEo1ioD!"
            - name: JAEGER_SERVICE_NAME
              value: "gateway"
            - name: JAEGER_COLLECTOR_HOST
              value: "jaeger-collector"
            - name: JAEGER_COLLECTOR_PORT
              value: "14268"
            - name: JAEGER_AGENT_HOST
              value: "jaeger-agent"
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: SAMPELLING_PROB
              value: "1"
          resources:
            requests:
              memory: "256Mi"
              cpu: 0.25
            limits:
              memory: "256Mi"
              cpu: 0.25
---
apiVersion: v1
kind: Service
metadata:
  name: gateway #this will be the Domain name
spec:
  selector:
    app: gateway
  ports:
    - port: 9080
      targetPort: 8080
  type: LoadBalancer
